# Generated by Django 3.2.15 on 2025-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_rank_analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_all', models.CharField(max_length=64, null=True)),
                ('jiji_add', models.CharField(max_length=64, null=True)),
                ('zhongxing_add', models.CharField(max_length=64, null=True)),
                ('xiaoji_add', models.CharField(max_length=64, null=True)),
                ('zhishu_all', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeepSeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField(null=True)),
                ('share_num', models.CharField(max_length=64, null=True)),
                ('comment_num', models.CharField(max_length=64, null=True)),
                ('like_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feel_analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField(null=True)),
                ('share_num', models.CharField(max_length=64, null=True)),
                ('comment_num', models.CharField(max_length=64, null=True)),
                ('like_num', models.CharField(max_length=64, null=True)),
                ('href', models.URLField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feel_analyse2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField(null=True)),
                ('share_num', models.CharField(max_length=64, null=True)),
                ('comment_num', models.CharField(max_length=64, null=True)),
                ('like_num', models.CharField(max_length=64, null=True)),
                ('href', models.URLField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feel_analyse3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField(null=True)),
                ('share_num', models.CharField(max_length=64, null=True)),
                ('comment_num', models.CharField(max_length=64, null=True)),
                ('like_num', models.CharField(max_length=64, null=True)),
                ('href', models.URLField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hot_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64, null=True)),
                ('hot_title', models.CharField(max_length=64, null=True)),
                ('hot_href', models.CharField(max_length=2048, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hot_rank_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10, verbose_name='排名')),
                ('hot_title', models.CharField(max_length=255, verbose_name='热搜标题')),
                ('hot_href', models.URLField(max_length=2048, verbose_name='链接')),
                ('hot_num', models.CharField(max_length=20, verbose_name='热度值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='nezha2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField(null=True)),
                ('share_num', models.CharField(max_length=64, null=True)),
                ('comment_num', models.CharField(max_length=64, null=True)),
                ('like_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='task_list_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tiyu_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64, null=True)),
                ('hot_title', models.CharField(max_length=64, null=True)),
                ('hot_href', models.CharField(max_length=2048, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tiyu_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='wanhui_315',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField(null=True)),
                ('share_num', models.CharField(max_length=64, null=True)),
                ('comment_num', models.CharField(max_length=64, null=True)),
                ('like_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wenyu_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xiaoyuan_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64, null=True)),
                ('hot_title', models.CharField(max_length=64, null=True)),
                ('hot_href', models.CharField(max_length=2048, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xiaoyuan_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yaowen_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_title', models.CharField(max_length=64, null=True)),
                ('hot_href', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yaowen_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='youxi_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64, null=True)),
                ('hot_title', models.CharField(max_length=64, null=True)),
                ('hot_href', models.CharField(max_length=2048, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='youxi_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiji', models.CharField(max_length=64, null=True)),
                ('zhongxing', models.CharField(max_length=64, null=True)),
                ('xiaoji', models.CharField(max_length=64, null=True)),
                ('num', models.CharField(max_length=64, null=True)),
                ('key_s', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yule_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64, null=True)),
                ('hot_title', models.CharField(max_length=64, null=True)),
                ('hot_href', models.CharField(max_length=2048, null=True)),
                ('hot_num', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
