# Generated by Django 3.2.15 on 2025-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_hot_rank_result_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiyu_result',
            name='href',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='wenyu_result',
            name='href',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='xiaoyuan_result',
            name='href',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='yaowen_result',
            name='href',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='youxi_result',
            name='href',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
